# Generated by Django 2.2.2 on 2019-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190623_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/IMG_1294.jpeg', null=True, upload_to='images/'),
        ),
    ]
